# Generated by Django 3.2.25 on 2024-04-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='the_admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='the_client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='the_trainer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='The_Admin',
        ),
        migrations.DeleteModel(
            name='The_Client',
        ),
        migrations.DeleteModel(
            name='The_Trainer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
